export const MutationKey = {
  CREATE_BOARD: "CREATE_BOARD",
  GET_BOARD: "GET_BOARD",
  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  MOVE_TASK: "MOVE_TASK",
} as const;
